# Generated by Django 2.2.9 on 2020-01-23 22:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("gwauth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Verification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("information", models.CharField(max_length=1024)),
                ("expiry", models.DateTimeField(null=True)),
                ("verified", models.BooleanField(default=False)),
            ],
        ),
    ]
