# Generated by Django 2.2.9 on 2020-01-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gwauth", "0002_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="gwclouduser",
            name="role",
            field=models.CharField(
                choices=[("Admin", "Admin"), ("User", "User")],
                default="User",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="gwclouduser",
            name="status",
            field=models.CharField(
                choices=[
                    ("Unverified", "Unverified"),
                    ("Verified", "Verified"),
                    ("Confirmed", "Confirmed"),
                    ("Deleted", "Deleted"),
                ],
                default="Unverified",
                max_length=10,
            ),
        ),
    ]
