# Generated by Django 2.2.14 on 2020-10-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwauth', '0004_gwclouduser_is_ligo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gwclouduser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
