# Generated by Django 2.2.17 on 2021-02-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwauth', '0007_apitoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='token',
            field=models.CharField(blank=True, default=None, max_length=64, unique=True),
        ),
    ]
