# Generated by Django 2.2.17 on 2021-02-19 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwauth', '0009_auto_20210219_0043'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apitoken',
            unique_together={('user', 'app')},
        ),
    ]
