# Generated by Django 2.2.17 on 2022-06-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwauth', '0010_auto_20210219_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='app',
            field=models.CharField(choices=[('gwcloud', 'GWCloud'), ('gwlab', 'GWLab'), ('gwlandscape', 'GWLandscape')], default='gwcloud', max_length=32),
        ),
    ]
