apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prd.yml
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.prd.yml
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: gwcloud_auth
        - name: MYSQL_PASSWORD
          value: 76vcqmGKP19Z1AEx
        - name: MYSQL_ROOT_PASSWORD
          value: 76vcqmGKP19Z1AEx
        - name: MYSQL_USER
          value: django
        image: mysql:5.7
        name: mysql-gwcloud-auth
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: var-lib-mysql
      restartPolicy: Always
      volumes:
      - name: var-lib-mysql
        persistentVolumeClaim:
          claimName: var-lib-mysql
status: {}
