apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: vault-agent
    app.kubernetes.io/instance: auth 
  name: secrets-integrator-auth
  namespace: gwcloud
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      labels:
        app: vault-kube-integrator
    spec:
      backoffLimit: 1
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-init-first: 'true'
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/agent-inject-secret-auth.yaml: gwcloud/kv/auth
            vault.hashicorp.com/agent-inject-template-auth.yaml: |
              {{- with secret "gwcloud/kv/auth" -}}
              apiVersion: v1
              kind: Secret
              type: Opaque
              data:
                {{ range $k, $v := .Data.data }}
                {{ $k }}: {{ $v }}
                {{ end }}
              metadata:
                namespace: gwcloud
                name: auth
              {{- end }}
            vault.hashicorp.com/agent-pre-populate-only: 'true'
            vault.hashicorp.com/agent-inject-secret-common.yaml: gwcloud/kv/common
            vault.hashicorp.com/agent-inject-template-common.yaml: |
              {{- with secret "gwcloud/kv/common" -}}
              apiVersion: v1
              kind: Secret
              metadata:
                namespace: gwcloud
                name: common
              type: Opaque
              data:
                {{ range $k, $v := .Data.data }}
                {{ $k }}: {{ $v }}
                {{ end }}
              {{- end }}
            vault.hashicorp.com/role: auth 
        spec:
          containers:
            - command:
                - kubectl
                - apply
                - '-f'
                - /vault/secrets/
              image: 'bitnami/kubectl:1.17.4'
              imagePullPolicy: IfNotPresent
              name: auth-vault-kube-integrator
              resources: {}
          imagePullSecrets:
            - name: regcred
          restartPolicy: Never
          serviceAccountName: auth 
  schedule: '* * * * *'
  successfulJobsHistoryLimit: 1
