---
# NodePort service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: gwcloud-auth
  name: gwcloud-auth
  namespace: gwcloud
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: port-1
    nodePort: 31602
    port: 80
    protocol: TCP
    targetPort: 80
  - name: port-2
    nodePort: 30201
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    name: gwcloud-auth
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
...
