---
# 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gwcloud-auth
  namespace: gwcloud
  labels:
    name: gwcloud-auth
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        name: gwcloud-auth
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          valueFrom:
          secretKeyRef:
            name: django-secret
            key: MYSQL_DATABASE
        - name: MYSQL_HOST
          valueFrom:
          secretKeyRef:
            name: django-secret
            key: MYSQL_HOST
        - name: MYSQL_PASSWORD
          valueFrom:
          secretKeyRef:
            name: django-secret
            key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
          secretKeyRef:
            name: django-secret
            key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
          secretKeyRef:
            name: django-secret
            key: MYSQL_USER
        - name: SECRET_KEY
          valueFrom:
          secretKeyRef:
            name: django-secret
            key: SECRET_KEY
        - name: SECRET_CAPTCHA
          valueFrom:
          secretKeyRef:
            name: django-secret
            key: SECRET_CAPTCHA
        name: gwcloud-auth
        image: nexus.gw-cloud.org/gwcloud-dev/gwcloud_auth:0.7
        ports:
        - name: http
          containerPort: 8000
        resources: {}
        tty: true
      imagePullSecrets:
      - name: regcred
... 
