---
# 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gwcloud-auth
  namespace: gwcloud
  labels:
    name: gwcloud-auth
spec:
  replicas: 1
  selector:
    matchLabels:
        name: gwcloud-auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        name: gwcloud-auth
    spec:
      containers:
      - envFrom:
          - secretRef:
              name: gwcloud-auth
          - secretRef:
              name: common
        name: gwcloud-auth
        image: nexus.gwdc.org.au/docker/gwcloud_auth:0.32
        ports:
        - name: http
          containerPort: 8000
        resources: {}
        tty: true
      imagePullSecrets:
      - name: regcred
... 
