apiVersion: v1
kind: Service
metadata:
  labels:
    name: gwcloud-auth
  name: gwcloud-auth
  namespace: gwcloud
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    name: gwcloud-auth
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}