apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: gwc-auth
  name: gwc-auth
  namespace: gwcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
      volume: gwc-auth
  volumeMode: Filesystem
  volumeName: gwc-auth
