apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: gwcloud-auth-db
  name: gwcloud-auth-db
  namespace: gwcloud
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    io.kompose.service: gwcloud-auth-db
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}